### ISSUE TITLE
doesn't build on 7.10 :(

### ISSUE THREAD

**Issue by cartazio** [kosmikus/safeint#9]
the usual primop Bool Int# stuff,
    `Couldn't match expected type ‘Bool’ with actual type ‘Int#’`

**Comment by kosmikus** [comment]
Sorry, yes. I've shamefully neglected this package for a long time. I'll try to get it back up and running.

**Comment by kosmikus** [comment]
@cartazio Just released 0.6 which hopefully works on 7.10.
